Insert Into PLAN_CATEGORY_NAME_ENTITY (CATEGORY_NAME_ID, CATEGORY_NAME) Values(1,'Food Plan');
Insert Into PLAN_CATEGORY_NAME_ENTITY (CATEGORY_NAME_ID, CATEGORY_NAME) Values(2,'Medical Plan');
Insert Into PLAN_CATEGORY_NAME_ENTITY (CATEGORY_NAME_ID, CATEGORY_NAME) Values(3,'Child Plan');
Insert Into PLAN_CATEGORY_NAME_ENTITY (CATEGORY_NAME_ID, CATEGORY_NAME) Values(4,'Unemployement Plan');
